/**
 * Provincias y principales localidades de la República Argentina
 */
export const ARGENTINA_PROVINCES = [
  "Ciudad Autónoma de Buenos Aires (CABA)",
  "Buenos Aires",
  "Catamarca",
  "Chaco",
  "Chubut",
  "Córdoba",
  "Corrientes",
  "Entre Ríos",
  "Formosa",
  "Jujuy",
  "La Pampa",
  "La Rioja",
  "Mendoza",
  "Misiones",
  "Neuquén",
  "Río Negro",
  "Salta",
  "San Juan",
  "San Luis",
  "Santa Cruz",
  "Santa Fe",
  "Santiago del Estero",
  "Tierra del Fuego",
  "Tucumán",
];

export const ARGENTINA_CITIES_BY_PROVINCE = {
  "Ciudad Autónoma de Buenos Aires (CABA)": [
    "Palermo",
    "Recoleta",
    "Belgrano",
    "Caballito",
    "Almagro",
    "Villa Urquiza",
    "Flores",
    "Balvanera",
    "San Telmo",
    "Nuñez",
    "Colegiales",
    "Villa Crespo",
    "Barracas",
    "Boedo",
    "Chacarita",
    "Saavedra",
    "Devoto",
    "Puerto Madero",
    "Retiro",
  ],
  "Buenos Aires": [
    "La Plata",
    "Mar del Plata",
    "Bahía Blanca",
    "San Isidro",
    "Vicente López",
    "Tigre",
    "San Fernando",
    "Pilar",
    "Escobar",
    "Quilmes",
    "Lanús",
    "Lomas de Zamora",
    "Avellaneda",
    "Morón",
    "Ramos Mejía",
    "San Justo",
    "Castelar",
    "Ituzaingó",
    "Merlo",
    "Moreno",
    "San Martín",
    "Tres de Febrero",
    "Hurlingham",
    "Tandil",
    "Olavarría",
    "Pergamino",
    "Junín",
    "Necochea",
    "Campana",
    "Zárate",
  ],
  "Córdoba": [
    "Córdoba Capital",
    "Villa Carlos Paz",
    "Río Cuarto",
    "Villa María",
    "Alta Gracia",
    "San Francisco",
    "Jesús María",
    "Río Tercero",
    "Bell Ville",
    "La Falda",
    "Cosquín",
    "Mina Clavero",
    "Santa Rosa de Calamuchita",
  ],
  "Santa Fe": [
    "Rosario",
    "Santa Fe Capital",
    "Rafaela",
    "Venado Tuerto",
    "Reconquista",
    "Santo Tomé",
    "Esperanza",
    "Villa Gobernador Gálvez",
    "Granadero Baigorria",
    "San Lorenzo",
  ],
  "Mendoza": [
    "Mendoza Capital",
    "San Rafael",
    "Godoy Cruz",
    "Guaymallén",
    "Las Heras",
    "Luján de Cuyo",
    "Maipú",
    "San Martín",
    "Tunuyán",
    "Malargüe",
  ],
  "San Luis": [
    "San Luis Capital",
    "Villa Mercedes",
    "Merlo",
    "La Punta",
    "Juana Koslay",
    "Justo Daract",
    "Santa Rosa del Conlara",
    "Concarán",
    "Tilisarao",
  ],
  "Entre Ríos": [
    "Paraná",
    "Concordia",
    "Gualeguaychú",
    "Concepción del Uruguay",
    "Villaguay",
    "Chajarí",
    "Gualeguay",
    "Colón",
  ],
  "Tucumán": [
    "San Miguel de Tucumán",
    "Yerba Buena",
    "Tafí Viejo",
    "Banda del Río Salí",
    "Aguilares",
    "Concepción",
    "Famaillá",
    "Tafí del Valle",
  ],
  "Salta": [
    "Salta Capital",
    "San Ramón de la Nueva Orán",
    "Tartagal",
    "General Güemes",
    "Rosario de la Frontera",
    "Cafayate",
    "San Lorenzo",
  ],
  "Misiones": [
    "Posadas",
    "Oberá",
    "Eldorado",
    "Puerto Iguazú",
    "Apóstoles",
    "Leandro N. Alem",
    "San Vicente",
  ],
  "Chaco": [
    "Resistencia",
    "Presidencia Roque Sáenz Peña",
    "Barranqueras",
    "Fontana",
    "Villa Ángela",
    "Castelli",
    "Charata",
  ],
  "Corrientes": [
    "Corrientes Capital",
    "Goya",
    "Paso de los Libres",
    "Curuzú Cuatiá",
    "Mercedes",
    "Bella Vista",
    "Monte Caseros",
  ],
  "Santiago del Estero": [
    "Santiago del Estero Capital",
    "La Banda",
    "Termas de Río Hondo",
    "Frías",
    "Añatuya",
    "Quimilí",
  ],
  "San Juan": [
    "San Juan Capital",
    "Rawson",
    "Rivadavia",
    "Chimbas",
    "Santa Lucía",
    "Pocito",
    "Caucete",
    "Jáchal",
  ],
  "Jujuy": [
    "San Salvador de Jujuy",
    "Palpalá",
    "San Pedro de Jujuy",
    "Libertador General San Martín",
    "Perico",
    "Tilcara",
    "Humahuaca",
  ],
  "Río Negro": [
    "San Carlos de Bariloche",
    "General Roca",
    "Cipolletti",
    "Viedma",
    "Villa Regina",
    "Cinco Saltos",
    "El Bolsón",
  ],
  "Neuquén": [
    "Neuquén Capital",
    "San Martín de los Andes",
    "Plottier",
    "Centenario",
    "Cutral Có",
    "Zapala",
    "Villa La Angostura",
  ],
  "Formosa": [
    "Formosa Capital",
    "Clorinda",
    "Pirané",
    "El Colorado",
    "Las Lomitas",
  ],
  "Chubut": [
    "Comodoro Rivadavia",
    "Trelew",
    "Puerto Madryn",
    "Esquel",
    "Rawson",
    "Rada Tilly",
  ],
  "Catamarca": [
    "San Fernando del Valle de Catamarca",
    "Valle Viejo",
    "Andalgalá",
    "Belén",
    "Tinogasta",
    "Santa María",
  ],
  "La Rioja": [
    "La Rioja Capital",
    "Chilecito",
    "Aimogasta",
    "Chamical",
    "Chepes",
    "Villa Unión",
  ],
  "La Pampa": [
    "Santa Rosa",
    "General Pico",
    "Toay",
    "Realicó",
    "Eduardo Castex",
    "General Acha",
  ],
  "Santa Cruz": [
    "Río Gallegos",
    "Caleta Olivia",
    "El Calafate",
    "Pico Truncado",
    "Las Heras",
    "Puerto Deseado",
  ],
  "Tierra del Fuego": [
    "Ushuaia",
    "Río Grande",
    "Tolhuin",
  ],
};
